version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./web/:/var/www/html
    environment:
      - APP_ENV=production
      - APP_DEBUG=false